neutron: Add ability to specify agent_boot_time
sap-oc/crowbar-openstack pull request #37
Opened 2017-05-09 07:58 UTC by vuntz

Closes https://github.com/sap-oc/crowbar-openstack/issues/36

2017-05-09 09:14 UTC, vuntz commented
For the record, patch for master: https://github.com/crowbar/crowbar-openstack/issues/962

2017-05-11 14:19 UTC, matelakat requested changes
DOn't we need a migration script?

2017-05-11 14:19 UTC, matelakat commented on chef/cookbooks/neutron/recipes/server.rb
> +      l2pop_settings: node[:neutron][:l2pop]
I prefer not to pass down the whole hash, just the value. This way we are exposing the internal structure of `l2pop` for the template.

2017-05-11 14:21 UTC, vuntz commented
> DOn't we need a migration script?

No, the new attributes are marked as "not required", so no migration is needed in that case (which is nice here, because we don't need to diverge from Cloud 6 in terms of revisions)

2017-05-11 14:52 UTC, matelakat approved these changes
Thanks for the clarification @vuntz

2017-08-14 09:21 UTC, tpatzig approved these changes

2017-08-14 11:29 UTC, merged